/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        manrope: ["manrope", "sans-serif"],
      },
      colors: {
        "primary-1": "var(--primary-1)",
        "primary-2": "var(--primary-2)",
        "primary-3": "var(--primary-3)",
        "primary-4": "var(--primary-4)",
        "primary-5": "var(--primary-5)",
        "secondary-1": "var(--secondary-1)",
        "secondary-2": "var(--secondary-2)",
        "secondary-3": "var(--secondary-3)",
        "secondary-4": "var(--secondary-4)",
        "secondary-5": "var(--secondary-5)",
        "success-1": "var(--success-1)",
        "success-2": "var(--success-2)",
        "success-3": "var(--success-3)",
        "success-4": "var(--success-4)",
        "warning-1": "var(--warning-1)",
        "warning-2": "var(--warning-2)",
        "warning-3": "var(--warning-3)",
        "error-1": "var(--error-1)",
        "error-2": "var(--error-2)",
        "error-3": "var(--error-3)",
        "error-4": "var(--error-4)",
        "gray-50": "var(--gray-50)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-300": "var(--gray-300)",
        "gray-400": "var(--gray-400)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-800": "var(--gray-800)",
        "gray-900": "var(--gray-900)",
        white: "var(--white)",
        orange: "var(--orange)",
        amber: "var(--amber)",
        purple: "var(--purple)",
      },
      fontSize: {
        10: "var(--font-s-10)",
        12: "var(--font-s-12)",
        14: "var(--font-s-14)",
        16: "var(--font-s-16)",
        20: "var(--font-s-20)",
        24: "var(--font-s-24)",
        32: "var(--font-s-32)",
        40: "var(--font-s-40)",
        48: "var(--font-s-48)",
      },
      fontWeight: {
        400: "var(--font-w-400)",
        500: "var(--font-w-500)",
        600: "var(--font-w-600)",
        700: "var(--font-w-700)",
        800: "var(--font-w-800)",
        900: "var(--font-w-900)",
      },
      lineHeight: {
        20: "var(--line-h-20)",
        30: "var(--line-h-30)",
        68: "var(--line-h-68)",
      },
      keyframes: {},
      animation: {},
    },
  },
  darkMode: ["selector", '[data-mode="dark"]'],
  plugins: [],
};
