/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        manrope: ["manrope", "sans-serif"],
      },
      colors: {
        "primary-1": "rgb(var(--primary-1), <alpha-value>)",
        "primary-2": "rgb(var(--primary-2), <alpha-value>)",
        "primary-3": "rgb(var(--primary-3), <alpha-value>)",
        "primary-4": "rgb(var(--primary-4), <alpha-value>)",
        "primary-5": "rgb(var(--primary-5), <alpha-value>)",
        "secondary-1": "rgb(var(--secondary-1), <alpha-value>)",
        "secondary-2": "rgb(var(--secondary-2), <alpha-value>)",
        "secondary-3": "rgb(var(--secondary-3), <alpha-value>)",
        "secondary-4": "rgb(var(--secondary-4), <alpha-value>)",
        "secondary-5": "rgb(var(--secondary-5), <alpha-value>)",
        "success-1": "rgb(var(--success-1), <alpha-value>)",
        "success-2": "rgb(var(--success-2), <alpha-value>)",
        "success-3": "rgb(var(--success-3), <alpha-value>)",
        "success-4": "rgb(var(--success-4), <alpha-value>)",
        "warning-1": "rgb(var(--warning-1), <alpha-value>)",
        "warning-2": "rgb(var(--warning-2), <alpha-value>)",
        "warning-3": "rgb(var(--warning-3), <alpha-value>)",
        "error-1": "rgb(var(--error-1), <alpha-value>)",
        "error-2": "rgb(var(--error-2), <alpha-value>)",
        "error-3": "rgb(var(--error-3), <alpha-value>)",
        "error-4": "rgb(var(--error-4), <alpha-value>)",
        "gray-50": "rgb(var(--gray-50), <alpha-value>)",
        "gray-100": "rgb(var(--gray-100), <alpha-value>)",
        "gray-200": "rgb(var(--gray-200), <alpha-value>)",
        "gray-300": "rgb(var(--gray-300), <alpha-value>)",
        "gray-400": "rgb(var(--gray-400), <alpha-value>)",
        "gray-500": "rgb(var(--gray-500), <alpha-value>)",
        "gray-600": "rgb(var(--gray-600), <alpha-value>)",
        "gray-700": "rgb(var(--gray-700), <alpha-value>)",
        "gray-800": "rgb(var(--gray-800), <alpha-value>)",
        "gray-900": "rgb(var(--gray-900), <alpha-value>)",
        white: "rgb(var(--white), <alpha-value>)",
        orange: "rgb(var(--orange), <alpha-value>)",
        amber: "rgb(var(--amber), <alpha-value>)",
        purple: "rgb(var(--purple), <alpha-value>)",
      },
      fontSize: {
        10: "var(--font-s-10)",
        12: "var(--font-s-12)",
        14: "var(--font-s-14)",
        16: "var(--font-s-16)",
        20: "var(--font-s-20)",
        24: "var(--font-s-24)",
        32: "var(--font-s-32)",
        40: "var(--font-s-40)",
        48: "var(--font-s-48)",
      },
      fontWeight: {
        400: "var(--font-w-400)",
        500: "var(--font-w-500)",
        600: "var(--font-w-600)",
        700: "var(--font-w-700)",
        800: "var(--font-w-800)",
        900: "var(--font-w-900)",
      },
      lineHeight: {
        20: "var(--line-h-20)",
        30: "var(--line-h-30)",
        68: "var(--line-h-68)",
      },
      borderRadius: {
        "custom-1": "16px 16px 16px 4px",
        "custom-2": "16px 16px 4px 16px",
      },
      animation: {},
    },
  },
  darkMode: ["selector", '[data-mode="dark"]'],
  plugins: [],
};
